public with sharing class Assignment {
    public Assignment(){
        System.debug('constructor is called ');
        }
        public static string firstMethod(){
            System.debug('firstMethod=======');
            return null;
        }
        public static void secondMethod(){
            System.debug('secondMethod=======');
        }
        public string  thirdMethod(){
           System.debug('thirdMethod=======');
           return null;
        }
        public void fourthMethod(){
            System.debug('fourthMethod=======');
        }
}