public class NameOfEmployees {
    Public void EmployeeName(String firstName,String lastName,String dateOfBirth){
        List<String> emp= new List<String>();
        emp.add(firstName);
        emp.add(lastName);
        emp.add(dateOfBirth);
        emps.addAll(emp);
            
        System.debug('First Name :'+firstName);
        System.debug('Last Name :'+lastName);
        System.debug('Date of Birth :'+dateOfBirth);
    }
     List<String> emps = new List<String>();
}